version: 2
updates:
  # Enable version updates for Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "kreed"
    assignees:
      - "kreed"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      # AWS and cloud services
      aws-services:
        patterns:
          - "aws-*"
          - "lambda*"
          - "serde_dynamo"
        update-types:
          - "minor"
          - "patch"
      # Core async and serialization
      core-runtime:
        patterns:
          - "tokio*"
          - "serde*"
          - "futures"
          - "reqwest*"
          - "tracing*"
        update-types:
          - "minor"
          - "patch"
      # Domain-specific libraries
      domain-libs:
        patterns:
          - "geo*"
          - "fitparser*"
          - "base64"
          - "csv"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 3
    reviewers:
      - "kreed"
    assignees:
      - "kreed"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
