version: 2
updates:
  # Enable version updates for Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "kreed"
    assignees:
      - "kreed"
    commit-message:
      prefix: "cargo"
      include: "scope"
    groups:
      aws-sdk:
        patterns:
          - "aws-*"
          - "tokio*"
      lambda-runtime:
        patterns:
          - "lambda*"
          - "serde*"
      geospatial:
        patterns:
          - "geo*"
          - "geojson*"
          - "fitparser*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 5
    reviewers:
      - "kreed"
    assignees:
      - "kreed"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Enable version updates for Terraform/OpenTofu
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
    open-pull-requests-limit: 5
    reviewers:
      - "kreed"
    assignees:
      - "kreed"
    commit-message:
      prefix: "terraform"
      include: "scope"
