name: Deploy to AWS Lambda

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: us-west-2
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Run tests
      run: cargo test
      
    - name: Run clippy
      run: cargo clippy -- -D warnings

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Install Rust toolchain with Cargo Lambda
      uses: moonrepo/setup-rust@v1
      with:
        bins: cargo-lambda

    - name: Install Zig toolchain
      uses: mlugg/setup-zig@v2
      with:
        version: 0.14.1

    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-lambda-${{ hashFiles('**/Cargo.lock') }}
      
    - name: Build Lambda function
      run: cargo lambda build --release
 
    - name: List files
      run: ls -lh target/lambda/intervals-mapper
 
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lambda-deployment-package
        path: target/lambda/intervals-mapper

  test-tofu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: "1.8.0"
        
    - name: OpenTofu Format Check
      working-directory: terraform
      run: tofu fmt -check
      
    - name: OpenTofu Init
      working-directory: terraform
      run: tofu init -backend=false
      
    - name: OpenTofu Validate
      working-directory: terraform
      run: tofu validate

  deploy:
    needs: [build, test, test-tofu]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v5
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: lambda-deployment-package
        path: target/lambda/
  
    - name: List files
      run: find target/lambda
       
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Setup OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: "1.8.0"
        
    - name: OpenTofu Init
      working-directory: terraform
      run: tofu init
      
    - name: OpenTofu Plan
      working-directory: terraform
      run: tofu plan
      
    - name: OpenTofu Apply
      working-directory: terraform
      run: tofu apply -auto-approve

