name: Build Tippecanoe Layer

on:
  push:
    paths:
      - '.github/workflows/tippecanoe-layer.yml'
  workflow_dispatch:
    inputs:
      tippecanoe_version:
        description: 'Tippecanoe version/branch to build'
        required: true
        default: 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: kreed/ridelines-tippecanoe-layer

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-layer:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Create Dockerfile
      run: |
        cat > Dockerfile.layer << 'EOF'
        # Build stage
        FROM public.ecr.aws/lambda/provided:al2023 AS builder
        
        # Install build dependencies
        RUN dnf update -y && \
            dnf install -y gcc-c++ make sqlite-devel zlib-devel git
        
        # Clone and build tippecanoe
        WORKDIR /build
        RUN git clone https://github.com/felt/tippecanoe.git
        WORKDIR /build/tippecanoe
        ARG TIPPECANOE_VERSION=main
        RUN git checkout ${TIPPECANOE_VERSION}
        RUN make
        
        # Copy binaries and dependencies
        RUN mkdir -p /layer/bin /layer/lib
        RUN cp tippecanoe /layer/bin/
        RUN ldd /layer/bin/tippecanoe | grep "=> /" | awk '{print $3}' | xargs -I '{}' cp '{}' /layer/lib/ || true
        
        # Make binaries executable
        RUN chmod +x /layer/bin/*
        
        # Create layer zip
        WORKDIR /layer
        RUN zip -r /tippecanoe-layer.zip .
        
        # Final stage - package for GHCR
        FROM scratch
        COPY --from=builder /tippecanoe-layer.zip /layer-package.zip
        EOF
        
        echo "Tippecanoe layer Dockerfile created"

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push container image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.layer
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          TIPPECANOE_VERSION=${{ github.event.inputs.tippecanoe_version || 'main' }}
